name: npm-publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the npm package version'
        required: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: set version
        run: npm version ${{ github.event.inputs.version }}
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
